### ISSUE TITLE
 Request for Python Environment Details to Resolve Package Conflicts

### ISSUE THREAD

**Issue by yuliangzhang** [cai525/Transformer4SED#3] opened 2024-10-23 04:02 UTC
Hi, your papers are truly excellent. However, when I tried to reproduce the results, I encountered numerous package conflicts. Could you please provide the exact Python environment settings, such as an environment YAML file? This would help other researchers who are interested in your work to easily reproduce the results in your papers.  Thank you~

**Comment by cai525** [comment] 2024-10-23 07:44
Thank you for your interest in our work. Regarding the environment setup for the code, we actually tested the project on a fresh machine before release and successfully ran the code. Here are some suggestions that might help you run the project successfully as well:

- The operating system we used was Linux, with CUDA version 11.7 and Python version 3.8.19.

- The required packages are listed in the requirements.txt file, and you can install them via `pip install -r requirements.txt`.

- The package versions do not need to match exactly with those in requirements.txt. If you encounter version conflicts, you can try more flexible version ranges for specific packages.

- Some dependencies might be tricky to handle, such as the timm library. However, the project only uses specific features from these libraries. My suggestion is to clone these complex libraries locally, manually modify their dependency files(`setup.py`), such as by expanding the version ranges, and then install them by `pip install --editable ./` command. In my experience, this approach is very effective for resolving complex Python dependency issues.

Feel free to reach out if you run into any problems during reproduction.

**Comment by wawjwyy123** [comment] 2024-10-27 12:41
Hi，When I run the code, I get the following error: 
lib/python3.9/site-packages/torch/nn/modules/dropout.py", line 24, in __init__
    if p < 0 or p > 1:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
How can I solve this problem? Is it an issue with the timm version? My itmm ==0.6.13

**Comment by cai525** [comment] 2024-10-27 13:49
> Hi，When I run the code, I get the following error: lib/python3.9/site-packages/torch/nn/modules/dropout.py", line 24, in **init** if p < 0 or p > 1: TypeError: '<' not supported between instances of 'NoneType' and 'int' How can I solve this problem? Is it an issue with the timm version? My itmm ==0.6.13

More detailed error information is required for analysis the source of this bug. It seems that this error is caused by the incorrectly data type of dropout probability.  Can you  provide the complete error information? Or try to debug according to the error information, for it seems that the cause of this error is very clear.

**Comment by cai525** [comment] 2024-10-27 13:59
> Hi，When I run the code, I get the following error: lib/python3.9/site-packages/torch/nn/modules/dropout.py", line 24, in **init** if p < 0 or p > 1: TypeError: '<' not supported between instances of 'NoneType' and 'int' How can I solve this problem? Is it an issue with the timm version? My itmm ==0.6.13

In addition, the versions of timm and several other libraries that the project depends on will be manually completed as soon as possible. Since these libraries were installed in editable mode, they were not included when creating the requirements.txt file. I hope this can help.

**Comment by wawjwyy123** [comment] 2024-10-28 02:39
> > Hi，When I run the code, I get the following error: lib/python3.9/site-packages/torch/nn/modules/dropout.py", line 24, in **init** if p < 0 or p > 1: TypeError: '<' not supported between instances of 'NoneType' and 'int' How can I solve this problem? Is it an issue with the timm version? My itmm ==0.6.13
> 
> More detailed error information is required for analysis the source of this bug. It seems that this error is caused by the incorrectly data type of dropout probability. Can you provide the complete error information? Or try to debug according to the error information, for it seems that the cause of this error is very clear.

Hi，I did not change the code, the complete error message is as follows:
Traceback (most recent call last):
  File "/transfomer-sed/recipes/mlm/mlm_passt/main.py", line 169, in <module>
    main(iter)
  File "/transfomer-sed/recipes/mlm/mlm_passt/main.py", line 92, in main
    net = get_model_passt(configs)
  File "/transfomer-sed/recipes/mlm/mlm_passt/passt_mlm_setting.py", line 6, in get_model_passt
    net = PaSST_SED(**configs["PaSST_SED"])
  File "/transfomer-sed/src/models/passt/passt_sed.py", line 133, in __init__
    self.init_decoder(decoder_win_len, decoder_layer_num, decoder_pos_emd_len)
  File "/transfomer-sed/src/models/passt/passt_sed.py", line 166, in init_decoder
    self.decoder = TransformerXLDecoder(input_dim=self.decoder_dim,
  File "/transfomer-sed/src/models/transformer_decoder.py", line 95, in __init__
    self.encoder_blocks = nn.ModuleList([
  File "/transfomer-sed/src/models/transformer_decoder.py", line 96, in <listcomp>
    TransformerXL(input_dim,
  File "/transfomer-sed/src/models/transformer/transformerXL.py", line 26, in __init__
    super().__init__(dim, num_heads, mlp_ratio, qkv_bias, qk_scale, drop, attn_drop,
  File "/home/anaconda3/envs/rct/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 257, in __init__
    self.attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, attn_drop=attn_drop, proj_drop=drop)
  File "/home/anaconda3/envs/rct/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 213, in __init__
    self.proj_drop = nn.Dropout(proj_drop)
  File "/home/anaconda3/envs/rct/lib/python3.9/site-packages/torch/nn/modules/dropout.py", line 24, in __init__
    if p < 0 or p > 1:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by cai525** [comment] 2024-10-28 04:37
@wawjwyy123 Check the [latest commit](https://github.com/cai525/Transformer4SED/commit/3cab3de91c7f16028a056371378a4606b3a4853a) for the full library requirements.
```
...
timm==0.4.5
desed==1.3.7
sebbs==0.0.0
sed_scores_eval==0.0.3
```

**Comment by wawjwyy123** [comment] 2024-10-28 06:28
> @wawjwyy123 Check the [latest commit](https://github.com/cai525/Transformer4SED/commit/3cab3de91c7f16028a056371378a4606b3a4853a) for the full library requirements. Thank you for your correction.
> 
> ```
> ...
> timm==0.4.5
> desed==1.3.7
> sebbs==0.0.0
> sed_scores_eval==0.0.3
> ```

Thank you, however, some new questions have arisen: 
Traceback (most recent call last):
File "/transfomer-sed/recipes/mlm/mlm_passt/main.py", line 169, in <module>
main(iter)
File "/transfomer-sed/recipes/mlm/mlm_passt/main.py", line 150, in main
trainer.train(epoch)
File "/transfomer-sed/recipes/mlm/mlm_passt/train.py", line 26, in train
mel = self.net.module.get_feature_extractor()(wavs)
The File "anaconda3 / envs/RCT/lib/python3.9 / site - packages/torch/nn/modules/module. Py", line 1614, in __getattr__
raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PaSST_SED' object has no attribute 'module'

My torch version is the same as yours, so how do you solve this problem? Looking forward to your reply！

**Comment by cai525** [comment] 2024-10-28 06:53
As mentioned in the paper, two 3090 GPUs are required to run the program, and DataParallel(DP) is used. Therefore, this project used `self.net.module.get_feature_extractor()` instead of `self.net.get_feature_extractor()` to get the feature extractor. It seems that the error is caused by the wrong setting of DataParallel (for example, not using GPU).  In general, I suppose this has nothing to do with the library version.

**Comment by wawjwyy123** [comment] 2024-10-28 07:00
> As mentioned in the paper, two 3090 GPUs are required to run the program, and DataParallel(DP) is used. Therefore, this project used instead of to get the feature extractor. It seems that the error is caused by the wrong setting of DataParallel (for example, not using GPU). In general, I suppose this has nothing to do with the library version.`self.net.module.get_feature_extractor()``self.net.get_feature_extractor()`

thanks！

**Closed** 2024-10-28 07:02 UTC

**Comment by wawjwyy123** [comment] 2024-10-29 01:05
Why do I finish running cd./exps/mat-sed/base
./train.sh, the result is only psds1=0.036, psds2=0.404? How to get similar results psds1=0.587, psds2=0.79? Do I need to change the default epoch?
